### ISSUE TITLE
Collection support

### ISSUE THREAD

**Issue by salehjafarli** [ronaldbosma/FluentAssertions.ArgumentMatchers.Moq#12]
When Its.EquivalentTo used against collection, configuration parameter is based on collections itself, rather than object that is contained inside collection

```cs
var collection = new List<Person>();

Its.EquivalentTo(collection, opts => opts.Including(p=> p.Age)) //p parameter here is not Person class, but List<Person>
```

**Comment by salehjafarli** [comment]
Please check this [PR](https://github.com/ronaldbosma/FluentAssertions.ArgumentMatchers.Moq/pull/11), I assume something like this might work, thanks

**Comment by ronaldbosma** [comment]
PR #11 merged
