### ISSUE TITLE
FluentAssertions 6 compatibility

### ISSUE THREAD

**Issue by mikeu** [ronaldbosma/FluentAssertions.ArgumentMatchers.Moq#3]
Hi @ronaldbosma, first off, thank you for what looks to be almost exactly the tool I need right now! From the documentation and a small experiment under FluentAssertions 5, this does just what I need. Unfortunately, it's not working for me and the problem seems to be that I'm using a beta version of FluentAssertions 6. After encountering the problem below I made a quick experiment using some toy classes and FluentAssertions 5.10.3. Everything worked as expected until I made the single change of upgrading to v6, and the test broke.

The error I'm receiving is:
```
Message:
  System.MissingMethodException : Method not found: 'Void FluentAssertions.Primitives.ObjectAssertions.BeEquivalentTo(System.__Canon, System.Func`2<FluentAssertions.Equivalency.EquivalencyAssertionOptions`1<System.__Canon>,FluentAssertions.Equivalency.EquivalencyAssertionOptions`1<System.__Canon>>, System.String, System.Object[])'.
Stack Trace:
    Its.AreEquivalent[TValue](TValue actual, TValue expected, Func`2 config)
    <>c__DisplayClass1_0`1.<EquivalentTo>b__0(TValue actual)
    Match`1.Matches(Object argument, Type parameterType) line 177
    IMatcher.Matches(Object argument, Type parameterType) line 78
    InvocationShape.IsMatch(Invocation invocation) line 132
    WhereArrayIterator`1.MoveNext()
    Mock.GetMatchingInvocationCount(Mock mock, ImmutablePopOnlyStack`1& parts, HashSet`1 visitedInnerMocks, List`1 invocationsToBeMarkedAsVerified) line 467
    Mock.GetMatchingInvocationCount(Mock mock, LambdaExpression expression, List`1& invocationsToBeMarkedAsVerified) line 439
    Mock.Verify(Mock mock, LambdaExpression expression, Times times, String failMessage) line 323
    Mock`1.Verify(Expression`1 expression) line 723
```

The code that throws the exception is basically from the readme:
```c#
mock.Verify(m => m.DoSomething(Its.EquivalentTo(
    expected,
    options => options.Excluding(b => b.Id)
)));
```

I'm using:
* FluentAssertions.ArgumentMatchers.Moq 1.0.0
* FluentAssertions 6.0.0-beta1
* Moq 4.16.1
* xunit 2.4.1
* .NET 5.0

---

I tried investigating this a bit, and found that indeed there is a void method with the given signature in the `MissingMethodException` in the FluentAssertions [v5 `ObjectAssertions` class](https://github.com/fluentassertions/fluentassertions/blob/5.10.3/Src/FluentAssertions/Primitives/ObjectAssertions.cs#L106-L108), while a method with the same name and arguments [exists in the v6 class](https://github.com/fluentassertions/fluentassertions/blob/release-6.0/Src/FluentAssertions/Primitives/ObjectAssertions.cs#L123-L125), but it is no longer void. What I haven't figured out yet is why the code in this library ends up throwing an exception because that method has a return type.

Do you have any plans to support FluentAssertions 6, or any thoughts on why this change has caused a problem here?

**Comment by ronaldbosma** [comment]
Hi @mikeu, great to hear that you've found this package useful. I am planning to support the new version of FluentAssertions when it's released.

I just did a little test with the solution on this branch: https://github.com/ronaldbosma/FluentAssertions.ArgumentMatchers.Moq/tree/3/fluent-assertions-6-compatibility. It's using version 6.0.0-beta0001 and doesn't seem to have a problem with the new version. All tests are green.

I think it might be a bug in the new FluentAssertions version. Maybe in combination with the object structures you're comparing. Do you have a public branch I can have a look at for the exception?

**Comment by ronaldbosma** [comment]
Now that I'm thinking about it. Are you using my public version of the FluentAssertions.ArgumentMatchers.Moq package or did you create your own version that allows a dependency to FluentAssertions v6?

If you're using the public version of FluentAssertions.ArgumentMatchers.Moq, my code might indeed expect a `BeEquivalentTo` that returns `void`. Which doesn't match with version 6 of FluentAssertions that you're using in your project.

**Comment by mikeu** [comment]
@ronaldbosma I am indeed just using the published package, installed from nuget. Didn't notice that you had that v6 compatibility branch on the go already, sorry! I don't have a public branch ready to go, but I could put a quick demo together to share if you thought it would still be useful—but from the sounds of things you're already aware of this and I just have to wait for a new release, or compile my own package, right?

Any chance you might publish a prerelease version that works with the FluentAssertions prereleases, or will you be holding off until they are stable?

**Comment by ronaldbosma** [comment]
Compiling your own package might be the quickest for now. When my holiday is over in a couple of weeks, I'll have a look at releasing a new version that also works with FluentAssertions 6.

**Comment by mikeu** [comment]
Sounds good, thanks for the confirmation of the issue, and already having a fix in progress! Enjoy your holiday :)
